name: CI cd
on:
  workflow_dispatch:
    # inputs:
    #   branch:
    #     description: 'The branch to build'
    #     required: true
    #   environment:
    #     description: 'The environment to deploy to'
    #     required: true
      


  # push:
  #   branches:
  #     - main
  #     - release
  #     - test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v3
        with:
          repository: davisgeorge/githubactions
          ref: ${{github.ref}}
          # ref: ${{ github.event.inputs.branch }}
          
            
    
        
      
    
      - name: Fetch existing tags
        run: git fetch --tags

      - name: Get the latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --always --abbrev=0)
          echo "::set-output name=tag::$latest_tag"

      - name: Extract version components
        id: extract_version
        run: |
          IFS='.' read -ra version <<< "${{ steps.get_latest_tag.outputs.tag }}"
          echo "::set-output name=major::${version[0]}"
          echo "::set-output name=minor::${version[1]}"
          echo "::set-output name=patch::${version[2]}"

      - name: Increment patch version
        id: increment_patch
        run: echo "::set-output name=patch::$((${{ steps.extract_version.outputs.patch }} + 1))"

      - name: Create new tag
        run: |
          new_tag="${{ steps.extract_version.outputs.major }}.${{ steps.extract_version.outputs.minor }}.${{ steps.increment_patch.outputs.patch }}"
          git tag -a -m "Release $new_tag" $new_tag
          git push --tags
  dev-relase:
    name: Deploy-Dev
    if: '${{ github.ref == ''refs/heads/release'' }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: release
      - name: this is dev branch
        run: |
          echo "this is dev-relase branch"
          git branch
  dev-test:
    name: Deploy-test
    if: '${{ github.ref == ''refs/heads/test'' }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: release
      - name: this is dev branch
        run: |
          echo "this is dev-test branch"
          git branch
