name: CI cd
on:
  workflow_dispatch:
    # inputs:
    #   branch:
    #     description: 'The branch to build'
    #     required: true
    #   environment:
    #     description: 'The environment to deploy to'
    #     required: true
      


  # push:
  #   branches:
  #     - main
  #     - release
  #     - test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v3
        with:
          repository: davisgeorge/githubactions
          ref: ${{github.ref}}
          # ref: ${{ github.event.inputs.branch }}
          
            
    
        
      
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Fetch tags
        run: git fetch --tags
  
      - name: Get latest tag
        id: get-latest-tag
        run: |
          tagFmt="^v?[0-9]+\.[0-9]+\.[0-9]+$"
          latest_tag=$(git for-each-ref --sort=-v:refname --format '%(refname:lstrip=2)' | grep -E "$tagFmt" | head -n 1)
          echo "::set-output name=tag::$latest_tag"
  
      - name: Extract major version
        id: extract-major-version
        run: |
          tag="$INPUT_TAG"  # Use the tag from the previous step
          [[ "$tag" =~ ^([0-9]+) ]]
          major=${BASH_REMATCH[1]}
          echo "::set-output name=major::$major"
  
      - name: Create new tag
        id: create-new-tag
        run: |
          major="$INPUT_MAJOR"  # Use the major version from the previous step
          git tag -a -m "New tag based on $INPUT_TAG" "$major"
          echo "::set-output name=new-tag::$major"
  
      - name: Push new tag
        run: |
          new_tag="$INPUT_NEW_TAG"  # Use the new tag from the previous step
          git push origin "$new_tag"

  dev-relase:
    name: Deploy-Dev
    if: '${{ github.ref == ''refs/heads/release'' }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: release
      - name: this is dev branch
        run: |
          echo "this is dev-relase branch"
          git branch
  dev-test:
    name: Deploy-test
    if: '${{ github.ref == ''refs/heads/test'' }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: release
      - name: this is dev branch
        run: |
          echo "this is dev-test branch"
          git branch
