name: CI
'on':
  push:
    branches:
      - master
      - release
      - test
  pull_request:
    branches:
      - master
      - release
      - test
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: 'echo Hello, world!'
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  dev-relase:
    name: Deploy-Dev
    if: github.repository == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: release
      - name: this is dev branch
        run: |
          echo "this is dev-relase branch"


          
      # - name: checkout to release
      #   uses: actions/checkout@v3
      #   with:
      #     ref: release
      # - name: push code
      #   run: |
      #     touch release-file.txt
      #     echo "Some release content" > release-file.txt
      #     echo "current working branch"
      #     git branch
      #     git config --global user.email "davis.work192@gmail.com"
      #     git config --global user.name "davisgeorge"
      #     git add .
      #     git commit -m "using github actions"
      #     git push origin
          

        
          # git config --global user.email "davis.work192@gmail.com"
          # git config --global user.name "davisgeorge"
          # git remote set-url origin https://github.com/davisgeorge/githubactions.git
          # git checkout release
          # git add .
          # git commit -m "Auto commit by Github Actions"
          # git push origin
      

